export const ERROR_CODES = {
  SUCCESS: 0,
  UNKNOWN_ERROR: 1000,
  PARAM_ERROR: 1001,
  UNAUTHORIZED: 1002,
  FORBIDDEN: 1003,
  NOT_FOUND: 1004,
  METHOD_NOT_ALLOWED: 1005,
  INTERNAL_ERROR: 1006,
  SERVICE_UNAVAILABLE: 1007,

  USER_NOT_FOUND: 2001,
  USER_BANNED: 2002,
  USER_EXISTS: 2003,
  LOGIN_FAILED: 2004,
  WECHAT_AUTH_FAILED: 2005,

  LEVEL_LOCKED: 3001,
  LEVEL_NOT_FOUND: 3002,
  LEVEL_COMPLETED: 3003,
  NO_TICKET: 3004,
  GAME_NOT_STARTED: 3005,
  GAME_ALREADY_ENDED: 3006,

  QUESTION_NOT_FOUND: 4001,
  ANSWER_ERROR: 4002,

  ITEM_NOT_FOUND: 5001,
  ITEM_SOLD_OUT: 5002,
  INSUFFICIENT_STARS: 5003,
  DAILY_LIMIT_EXCEEDED: 5004,

  ADMIN_NOT_FOUND: 6001,
  ADMIN_DISABLED: 6002,
  ADMIN_EXISTS: 6003,
  PASSWORD_ERROR: 6004,
  INVALID_CAPTCHA: 6005,

  DATABASE_ERROR: 7001,
  REDIS_ERROR: 7002,
  MONGODB_ERROR: 7003,
} as const;

export const STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const USER_STATUS = {
  NORMAL: 0,
  BANNED: 1,
  DELETED: 2,
} as const;

export const GENDER = {
  UNKNOWN: 0,
  MALE: 1,
  FEMALE: 2,
} as const;

export const REGION_TYPE = {
  COUNTRY: 1,
  PROVINCE: 2,
  CITY: 3,
} as const;

export const LEVEL_STATUS = {
  LOCKED: 0,
  UNLOCKED: 1,
  COMPLETED: 2,
} as const;

export const QUESTION_TYPE = {
  SINGLE_CHOICE: 1,
  MULTI_CHOICE: 2,
  TRUE_FALSE: 3,
  FILL_BLANK: 4,
  IMAGE_CHOICE: 5,
  AUDIO_CHOICE: 6,
} as const;

export const DIFFICULTY = {
  EASY: 1,
  MEDIUM: 2,
  HARD: 3,
  EXPERT: 4,
} as const;

export const ITEM_TYPE = {
  TICKET: 1,
  HINT: 2,
  SKIP: 3,
  TIME_EXTEND: 4,
  SHIELD: 5,
} as const;

export const ITEM_STATUS = {
  OFF_SHELF: 0,
  ON_SHELF: 1,
  SOLD_OUT: 2,
} as const;

export const ADMIN_STATUS = {
  NORMAL: 0,
  DISABLED: 1,
  DELETED: 2,
} as const;

export const ROLE_STATUS = {
  DISABLED: 0,
  ENABLED: 1,
} as const;

export const FEEDBACK_STATUS = {
  PENDING: 0,
  PROCESSING: 1,
  RESOLVED: 2,
  CLOSED: 3,
} as const;

export const FEEDBACK_TYPE = {
  BUG: 1,
  SUGGESTION: 2,
  COMPLAINT: 3,
  OTHER: 4,
} as const;

export const RECOMMEND_STATUS = {
  DRAFT: 0,
  PUBLISHED: 1,
  EXPIRED: 2,
} as const;

export const TICKET_CHANGE_TYPE = {
  PURCHASE: 1,
  CONSUME: 2,
  SYSTEM_GIFT: 3,
  LEVEL_REWARD: 4,
} as const;

export const ERROR_MESSAGES: Record<number, string> = {
  [ERROR_CODES.SUCCESS]: '操作成功',
  [ERROR_CODES.UNKNOWN_ERROR]: '未知错误',
  [ERROR_CODES.PARAM_ERROR]: '参数错误',
  [ERROR_CODES.UNAUTHORIZED]: '未授权',
  [ERROR_CODES.FORBIDDEN]: '禁止访问',
  [ERROR_CODES.NOT_FOUND]: '资源不存在',
  [ERROR_CODES.METHOD_NOT_ALLOWED]: '方法不允许',
  [ERROR_CODES.INTERNAL_ERROR]: '服务器内部错误',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: '服务不可用',

  [ERROR_CODES.USER_NOT_FOUND]: '用户不存在',
  [ERROR_CODES.USER_BANNED]: '用户已被封禁',
  [ERROR_CODES.USER_EXISTS]: '用户已存在',
  [ERROR_CODES.LOGIN_FAILED]: '登录失败',
  [ERROR_CODES.WECHAT_AUTH_FAILED]: '微信授权失败',

  [ERROR_CODES.LEVEL_LOCKED]: '关卡未解锁',
  [ERROR_CODES.LEVEL_NOT_FOUND]: '关卡不存在',
  [ERROR_CODES.LEVEL_COMPLETED]: '关卡已完成',
  [ERROR_CODES.NO_TICKET]: '门票不足',
  [ERROR_CODES.GAME_NOT_STARTED]: '游戏未开始',
  [ERROR_CODES.GAME_ALREADY_ENDED]: '游戏已结束',

  [ERROR_CODES.QUESTION_NOT_FOUND]: '题目不存在',
  [ERROR_CODES.ANSWER_ERROR]: '答案错误',

  [ERROR_CODES.ITEM_NOT_FOUND]: '商品不存在',
  [ERROR_CODES.ITEM_SOLD_OUT]: '商品已售罄',
  [ERROR_CODES.INSUFFICIENT_STARS]: '星星不足',
  [ERROR_CODES.DAILY_LIMIT_EXCEEDED]: '超过每日购买限制',

  [ERROR_CODES.ADMIN_NOT_FOUND]: '管理员不存在',
  [ERROR_CODES.ADMIN_DISABLED]: '管理员已禁用',
  [ERROR_CODES.ADMIN_EXISTS]: '管理员已存在',
  [ERROR_CODES.PASSWORD_ERROR]: '密码错误',
  [ERROR_CODES.INVALID_CAPTCHA]: '验证码错误',

  [ERROR_CODES.DATABASE_ERROR]: '数据库错误',
  [ERROR_CODES.REDIS_ERROR]: 'Redis错误',
  [ERROR_CODES.MONGODB_ERROR]: 'MongoDB错误',
};
