export const ERROR_CODE = {
  SUCCESS: 0,
  PARAM_ERROR: 1001,
  UNAUTHORIZED: 1002,
  FORBIDDEN: 1003,
  NOT_FOUND: 1004,
  INTERNAL_ERROR: 1005,

  USER_NOT_FOUND: 2001,
  USER_ALREADY_EXISTS: 2002,
  USER_NOT_INITIALIZED: 2003,

  LEVEL_NOT_FOUND: 3001,
  LEVEL_LOCKED: 3002,
  LEVEL_NOT_COMPLETED: 3003,

  QUESTION_NOT_FOUND: 4001,
  QUESTION_TYPE_INVALID: 4002,

  TICKET_INSUFFICIENT: 5001,
  TICKET_MAX_LIMIT: 5002,

  ITEM_NOT_FOUND: 6001,
  ITEM_INSUFFICIENT_STARS: 6002,
  ITEM_INSUFFICIENT_COINS: 6003,

  ADMIN_NOT_FOUND: 7001,
  ADMIN_PASSWORD_ERROR: 7002,
  ADMIN_LOCKED: 7003,
} as const;

export const ERROR_MESSAGE: Record<number, string> = {
  [ERROR_CODE.SUCCESS]: '成功',
  [ERROR_CODE.PARAM_ERROR]: '参数错误',
  [ERROR_CODE.UNAUTHORIZED]: '未授权',
  [ERROR_CODE.FORBIDDEN]: '无权限',
  [ERROR_CODE.NOT_FOUND]: '资源不存在',
  [ERROR_CODE.INTERNAL_ERROR]: '服务器内部错误',

  [ERROR_CODE.USER_NOT_FOUND]: '用户不存在',
  [ERROR_CODE.USER_ALREADY_EXISTS]: '用户已存在',
  [ERROR_CODE.USER_NOT_INITIALIZED]: '用户未初始化',

  [ERROR_CODE.LEVEL_NOT_FOUND]: '关卡不存在',
  [ERROR_CODE.LEVEL_LOCKED]: '关卡未解锁',
  [ERROR_CODE.LEVEL_NOT_COMPLETED]: '关卡未完成',

  [ERROR_CODE.QUESTION_NOT_FOUND]: '题目不存在',
  [ERROR_CODE.QUESTION_TYPE_INVALID]: '题目类型无效',

  [ERROR_CODE.TICKET_INSUFFICIENT]: '门票不足',
  [ERROR_CODE.TICKET_MAX_LIMIT]: '门票已达上限',

  [ERROR_CODE.ITEM_NOT_FOUND]: '商品不存在',
  [ERROR_CODE.ITEM_INSUFFICIENT_STARS]: '星星不足',
  [ERROR_CODE.ITEM_INSUFFICIENT_COINS]: '金币不足',

  [ERROR_CODE.ADMIN_NOT_FOUND]: '管理员不存在',
  [ERROR_CODE.ADMIN_PASSWORD_ERROR]: '密码错误',
  [ERROR_CODE.ADMIN_LOCKED]: '账号已锁定',
};
